version: 2
jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            ssh zeuty@155.94.181.128 "cd /home/zeuty/iamgu && git pull origin master"
workflows:
  version: 2
  ssh_deploy:
    jobs:
      - deploy
          filters:
            branches:
              only: master
